function colors = cneColors(z)
    colors = {[z z 1],[0 0 1],...
              [1 z z],[1 0 0],...
              [z 1 z],[0 1 0],...
              [z z z],[0 0 0],...
              [1 1 z],[1 1 0]};
end